// <auto-generated />
using System;
using LionttoMoveis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LionttoMoveis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511232126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LionttoMoveis.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes", t =>
                        {
                            t.HasCheckConstraint("CK_clientes_nome_not_blank", "CHAR_LENGTH(TRIM(nome)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.ItemDoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Personalizacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("personalizacoes");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("produto_nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("itens_do_pedido", t =>
                        {
                            t.HasCheckConstraint("CK_itens_do_pedido_produto_nome_not_blank", "CHAR_LENGTH(TRIM(produto_nome)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double")
                        .HasColumnName("quantidade");

                    b.Property<double>("QuantidadeMinima")
                        .HasColumnType("double")
                        .HasColumnName("quantidade_minima");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.ToTable("materiais", t =>
                        {
                            t.HasCheckConstraint("CK_materiais_nome_not_blank", "CHAR_LENGTH(TRIM(nome)) > 0");

                            t.HasCheckConstraint("CK_materiais_unidade_not_blank", "CHAR_LENGTH(TRIM(unidade)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.MaterialDoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_material");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<double>("QuantidadeNecessaria")
                        .HasColumnType("double")
                        .HasColumnName("quantidade_necessaria");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("materiais_do_produto", t =>
                        {
                            t.HasCheckConstraint("CK_materiais_do_produto_nome_not_blank", "CHAR_LENGTH(TRIM(nome_material)) > 0");

                            t.HasCheckConstraint("CK_materiais_do_produto_unidade_not_blank", "CHAR_LENGTH(TRIM(unidade)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_movimentacao");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("motivo");

                    b.Property<string>("NomeMaterial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_material");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double")
                        .HasColumnName("quantidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("movimentacoes", t =>
                        {
                            t.HasCheckConstraint("CK_movimentacoes_nome_material_not_blank", "CHAR_LENGTH(TRIM(nome_material)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cliente_nome");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEntregaPrevista")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_entrega_prevista");

                    b.Property<DateTime?>("DataEntregaReal")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_entrega_real");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_pedido");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("pedidos", t =>
                        {
                            t.HasCheckConstraint("CK_pedidos_cliente_nome_not_blank", "CHAR_LENGTH(TRIM(cliente_nome)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao_")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_base");

                    b.Property<int>("TempoProducaoDias")
                        .HasColumnType("int")
                        .HasColumnName("tempo_producao_dias");

                    b.HasKey("Id");

                    b.ToTable("produtos", t =>
                        {
                            t.HasCheckConstraint("CK_produtos_nome_not_blank", "CHAR_LENGTH(TRIM(nome)) > 0");
                        });
                });

            modelBuilder.Entity("LionttoMoveis.Models.ItemDoPedido", b =>
                {
                    b.HasOne("LionttoMoveis.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LionttoMoveis.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LionttoMoveis.Models.MaterialDoProduto", b =>
                {
                    b.HasOne("LionttoMoveis.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LionttoMoveis.Models.Produto", "Produto")
                        .WithMany("Materiais")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Movimentacao", b =>
                {
                    b.HasOne("LionttoMoveis.Models.Material", "Material")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Pedido", b =>
                {
                    b.HasOne("LionttoMoveis.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Material", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("LionttoMoveis.Models.Produto", b =>
                {
                    b.Navigation("Materiais");
                });
#pragma warning restore 612, 618
        }
    }
}
